### ISSUE TITLE
include this project on vertx-awesome page!

### ISSUE THREAD

**Issue by pmlopes** [dano/vertx-zeromq#1]
It would be nice to have it included here: https://github.com/vert-x3/vertx-awesome

**Comment by dano** [comment]
@pmlopes I'm planning on it! I only just got this up and running over the weekend, so I was waiting to clean a few things up before I posted about it on the mailing list/submitted a PR to vertx-awesome. I'll do both of those things soon, though!

**Comment by dano** [comment]
@pmlopes I've submitted the PR to vertx-awesome: https://github.com/vert-x3/vertx-awesome/pull/52

**Comment by pmlopes** [comment]
Thanks!
